%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

Name:           ros-humble-lidar-situational-graphs
Version:        0.0.1
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS lidar_situational_graphs package

License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       ceres-solver-devel
Requires:       ros-humble-ament-cmake-gtest
Requires:       ros-humble-backward-ros
Requires:       ros-humble-fast-gicp
Requires:       ros-humble-geodesy
Requires:       ros-humble-geographic-msgs
Requires:       ros-humble-geometry-msgs
Requires:       ros-humble-libg2o
Requires:       ros-humble-message-filters
Requires:       ros-humble-nav-msgs
Requires:       ros-humble-ndt-omp
Requires:       ros-humble-nmea-msgs
Requires:       ros-humble-pcl-ros
Requires:       ros-humble-rclcpp
Requires:       ros-humble-rclpy
Requires:       ros-humble-rviz-visual-tools
Requires:       ros-humble-sensor-msgs
Requires:       ros-humble-situational-graphs-msgs
Requires:       ros-humble-situational-graphs-reasoning
Requires:       ros-humble-situational-graphs-reasoning-msgs
Requires:       ros-humble-tf2
Requires:       ros-humble-tf2-eigen
Requires:       ros-humble-tf2-ros
Requires:       ros-humble-tf2-sensor-msgs
Requires:       ros-humble-visualization-msgs
Requires:       ros-humble-ros-workspace
BuildRequires:  ceres-solver-devel
BuildRequires:  ros-humble-ament-cmake
BuildRequires:  ros-humble-ament-cmake-gtest
BuildRequires:  ros-humble-ament-cmake-python
BuildRequires:  ros-humble-backward-ros
BuildRequires:  ros-humble-fast-gicp
BuildRequires:  ros-humble-geodesy
BuildRequires:  ros-humble-geographic-msgs
BuildRequires:  ros-humble-geometry-msgs
BuildRequires:  ros-humble-libg2o
BuildRequires:  ros-humble-message-filters
BuildRequires:  ros-humble-nav-msgs
BuildRequires:  ros-humble-ndt-omp
BuildRequires:  ros-humble-nmea-msgs
BuildRequires:  ros-humble-pcl-ros
BuildRequires:  ros-humble-rclcpp
BuildRequires:  ros-humble-rclpy
BuildRequires:  ros-humble-rviz-visual-tools
BuildRequires:  ros-humble-sensor-msgs
BuildRequires:  ros-humble-situational-graphs-msgs
BuildRequires:  ros-humble-situational-graphs-reasoning
BuildRequires:  ros-humble-situational-graphs-reasoning-msgs
BuildRequires:  ros-humble-tf2
BuildRequires:  ros-humble-tf2-eigen
BuildRequires:  ros-humble-tf2-ros
BuildRequires:  ros-humble-tf2-sensor-msgs
BuildRequires:  ros-humble-visualization-msgs
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-humble-ament-lint-auto
%endif

%description
The lidar situational graphs package for generating 3D optimizable scene graphs

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Thu Jun 27 2024 hriday <hriday.bavle@gmail.com> - 0.0.1-2
- Autogenerated by Bloom

